### ISSUE TITLE
Test fails at boilerplate, but seems to be another problem.

### ISSUE THREAD

**Issue by jinmayamashita** [monstar-lab-oss/ml-frontend#1014]
Test fails at boilerplate, but seems to be another problem.

_Originally posted by @jinmayamashita in https://github.com/monstar-lab-oss/ml-frontend/issues/711#issuecomment-1724933643_

**Comment by ptrkdan** [comment]
@jinmayamashita 
Just to confirm, has this issue been fixed by #1127?

**Comment by ptrkdan** [comment]
Confirmed that it was fixed by #1127!
