### ISSUE TITLE
[BUG] Encountering an error during MSW execution in browser.

### ISSUE THREAD

**Issue by jinmayamashita** [monstar-lab-oss/ml-frontend#1124]
## Describe the bug

An error in MSW occurs when executed in the browser, preventing it from running.

By the way, in the generated template, the path for the MSW mock server is also incorrect.

## To Reproduce

1. Run `create-codes` cli to complete the template setup.
1. Run `pnpm i` in the installed directory.
1. `pnpm dev` and connect to http://localhost:3000/ in the browser.
1. An error is occurring

## Expected behavior

`[MSW] Mocking enabled` is displayed in the browser console

## Related packages/templates

`create-codes`

## Screenshots (optional)

![Screenshot 2023-11-17 at 0 37 31](https://github.com/monstar-lab-oss/ml-frontend/assets/9401060/3d93e95c-e023-4b5e-b896-a13c4078f297)

## Additional context (optional)

There was a related issue. I tried it, but it didn't work as expected.

- https://github.com/mswjs/msw/issues/1655
- https://stackoverflow.com/questions/76995419/syntaxerror-unexpected-string-in-msw

**Comment by ptrkdan** [comment]
@jinmayamashita
Just to confirm, has this issue also been fixed by #1127?

**Comment by ptrkdan** [comment]
Confirmed that it was fixed by #1127!
