### ISSUE TITLE
[BUG] RESTful-related test code is falling.

### ISSUE THREAD

**Issue by jinmayamashita** [monstar-lab-oss/ml-frontend#1128]
## Describe the bug
The RESTful-related test code, which is not failing in the monorepo CI, fails after being generated by `create-codes`.

## To Reproduce
1. Run `create-codes` cli to complete the template setup.
1. Run `pnpm i` in the installed directory.
1. Run `pnpm test`
1. An error is occurring

## Expected behavior
The tests succeed when running the test execution script with `pnpm test` in the generated code.

## Related packages/templates
`react/module-api-restful`

## Screenshots (optional)

https://github.com/monstar-lab-oss/ml-frontend/pull/1127#issuecomment-1826390064

**Comment by ptrkdan** [comment]
> It still feels unresolved, doesn't it? 🤔

I was able to reproduce the test failure on my machine, so this still requires a fix. I'll take a look at it!
