### ISSUE TITLE
[BUG] The e2e tests for the generated code are failing.

### ISSUE THREAD

**Issue by jinmayamashita** [monstar-lab-oss/ml-frontend#1131]
## Describe the bug

The generated code seems to have a bug where the E2E test server is not responding.

## To Reproduce

```sh
? Where Would You like to Create Your Application? ./my-app
? Select a JavsScript library for UI React
? Select an API Solution RESTful
? Select module do you want to use Add CRUD Operations
? Add Testing codes for Catching bugs early? Yes
? Add Vitest for Unit Testing? Yes
? Add Storybook for Visual Testing? Yes
? Add Playwright for End-To-End Testing? Yes
? Add ESLint for Code Linting? No
? Add Prettier for Code Formatting? No
```

1. As with the above CLI option, choose the E2E test and execute the `create-codes` CLI to finalize the template setup.
2. Run `pnpm i && pnpm e2e`
3. An error similar to the following occurs

```sh
Running 4 tests using 2 workers

  ✘  1 About.test.ts:15:3 › About page › About page has title and 2 links (532ms)
  ✘  2 Home.test.ts:16:3 › Home page › Home page has a button and 2 links (508ms)
  ✘  3 Home.test.ts:33:3 › Home page › Move to about page (291ms)
  ✘  4 Home.test.ts:42:3 › Home page › Load message (424ms)


  1) About.test.ts:15:3 › About page › About page has title and 2 links ============================

    page.goto: net::ERR_CONNECTION_REFUSED at http://localhost:3000/about
    =========================== logs ===========================
    navigating to "http://localhost:3000/about", waiting until "load"
    ============================================================

       5 | test.beforeEach(async ({ browser }) => {
       6 |   page = await browser.newPage();
    >  7 |   await page.goto("/about");
         |              ^
       8 | });
       9 |
      10 | test.afterAll(async () => {
```

## Expected behavior
The E2E test is successful.

## Related packages/templates

- `create-codes`
- `e2e-testing`

**Comment by ptrkdan** [comment]
@jinmayamashita 
The title is pretty straightforward, but the description hasn't been filled out yet 😅 
If you could recall any relevant information regarding this issue, could you add it later? 
I'll try to reproduce it on my machine and add any useful information here

**Comment by ptrkdan** [comment]
It appears that when you run the `e2e` script by itself, it fails with a `page.goto: net::ERR_CONNECTION_REFUSED at http://localhost:3000/` error. When I run the `dev` or `start` script before running the e2e test, all tests pass.

I think need to add a [web server configuration](https://playwright.dev/docs/test-webserver#configuring-a-web-server) in the `playwright.config.ts` itself. 

```ts
webServer: {
  command: "npm run preview",
  url: "http://localhost:3000",
  reuseExistingServer: !CI,
}
```

I'll write a PR for this, but @jinmayamashita, if you were encountering a different issue, please let me know!

**Comment by ptrkdan** [comment]
Also, this is blocked by #1129. Tests fail without the global type definition
