### ISSUE TITLE
[BUG] When releasing, git tag isn't pushed

### ISSUE THREAD

**Issue by jinmayamashita** [monstar-lab-oss/ml-frontend#1213]
## To Reproduce

https://github.com/monstar-lab-oss/ml-frontend/actions/runs/8198926342/job/22423227560

## Related packages/templates
Repository packages (`start-frontend`, `e2e-testing`, etc.), or code template (`react/base`, etc.) that is related to the bug.

**Comment by ptrkdan** [comment]
It looks like this was fixed in the last release: https://github.com/monstar-lab-oss/ml-frontend/actions/runs/8369005577/job/22914038235#step:7:74

Therefore, I'm closing this issue. ✌️
