### ISSUE TITLE
Plan up to version 1.0.0

### ISSUE THREAD

**Issue by jinmayamashita** [monstar-lab-oss/ml-frontend#387]
## As is

The current boilerplate is Scoped only for React, and no flexibility in terms of functionality and testing is provided.

## To be

Front-end Developers will have the flexibility to choose the features and test libraries they wish to use in their projects, based on our proposed structure as a standard.

### Solution & Goal

We Provide command line tools for creating new front-end boilerplate. (At least with React alone)

### Specification

Our users: front-end developers

- Users can use the library/framework for building applications
- Users can use advanced pre-configured structures what we propose as standard
- Users can select the modules they wish to use[^1]
- Users can use the test libraries they want
- Our maintenance is easy

## Todo

The base branch will be [`next-v1`](https://github.com/monstar-lab-oss/reactjs-boilerplate/tree/next-v1) for the experimental stage.

- Users can use the library/framework for building applications
  - [x] #392
- Users can use advanced pre-configured structures what we propose as standard
  - [x] #427
- Users can select the modules they wish to use
  - [x] #391
  - [x] #390
- Users can use the test libraries they want
  - [x] #413
- Our maintenance is easy
  - [x] #388
  - [x] #394
  - ~~#414~~
- Bug fixes
  - [x] #768
  - [x] #774
- Publish to `npm` (prerelease?)
  - [ ] Git tag
  - [ ] Github package
  - [ ] Create Github actions to bump, publish using `changesets`
  - [ ] Publish `npm`

[^1]: https://github.com/monstar-lab-oss/reactjs-boilerplate/discussions/295#discussioncomment-4496635

## Sprint board

🏃🏼‍♂️ https://github.com/orgs/monstar-lab-oss/projects/2/views/4

**Comment by G-N555** [comment]
@jinmayamashita cc: @mvn-luanvu-hn @seiya0914 
thank you so much for creating the issue!

One thing, I just wondered is whether we should develop 1.0.0 step by step with making clear each steps.

I see unchecked todos above and feel that each of them are quite heavy, so we should focus on one by one instead take whatever available to be able to make everyone follow latest status with being on the same track.

Besides, the base branch `next-v1` seems to have entire react boilerplate files inside and not sure all folders/files are need for 1.0.0 or actually need to clean up.

So, I have a general idea about steps below.

1. clean up base branch code
2. set each order of steps for development based on todos above

Once we decide the order of todos, then we should create each subtasks based on each todo.
Then, running below cycle to develop.

1. Allocate each tasks to engineers with due date
2. Develop until due date
3. merge each developed task into base branch(or maybe feature branch split by base branch e.g. `feature/todo1`)
4. close task after merging, take another subtask when you have time

I understand that is kinda normal standard steps and probably everyone understand, but I feel would be good to make sure these steps before we start taking todos to avoid messy situation.
