### ISSUE TITLE
Not found page when unauthenticated state

### ISSUE THREAD

**Issue by jinmayamashita** [monstar-lab-oss/ml-frontend#409]
The `next-v1` branch currently redirects to the Login page unconditionally in the unauthenticated state, but is it necessary to have a `Not found` page even in the unauthenticated state?

_Originally posted by @jinmayamashita in https://github.com/monstar-lab-oss/reactjs-boilerplate/pull/408#discussion_r1084768051_

**Comment by ptrkdan** [comment]
Since the `next-v1` branch has already been closed, I'm closing this issue. If the issue persists, please create a new one.
