### ISSUE TITLE
Provide the use libraries/framework as an option

### ISSUE THREAD

**Issue by jinmayamashita** [monstar-lab-oss/ml-frontend#425]
## Overview

Users can choose from the latest trends in front-end libraries/frameworks to build their applications via cli

## To resolve this issue

- [x] #492
- [x] #490
- [ ] Create Next.js base codes (Optional)
- [x] #463 (Optional)
- [ ] Create Svelte base codes (Optional)
- [x] #487

## Note

Any implementation other than `Create React base codes` can be done after the 1.0.0 version.

**Comment by ptrkdan** [comment]
The scope for v1 release has been changed to only include React in the meantime.
Other frameworks will be included in future release.

**Comment by ptrkdan** [comment]
Since the scope right now is only for v1, I'm closing this issue for now. We will create a new issue when we decide to implement the other frameworks.
