### ISSUE TITLE
Users can find out how to use each modules and packages from the documentation

### ISSUE THREAD

**Issue by jinmayamashita** [monstar-lab-oss/ml-frontend#427]
## Overview

It would be nice if it could be documented how users can use the code generated by create-codes.

## To resolve this issue

- [x] #866
- [x] #867
- ~~#868~~
  - It might be useful to allow reuse in the cli modules descripion.
- [x] #869

**Comment by ptrkdan** [comment]
Current plan:
Include a quick explanation of each modules in the `create-codes` README.
If it becomes too cumbersome to maintain within the README, we will consider extract it to another location.
