### ISSUE TITLE
We need a more fitting folder name than "examples".

### ISSUE THREAD

**Issue by jinmayamashita** [monstar-lab-oss/ml-frontend#787]
## Description

Currently, the name of the folder containing the base code and modules code is "examples", but it has a different meaning from the usage of "examples".

## Context

https://github.com/monstar-lab-oss/reactjs-boilerplate/tree/react-base/examples

## Possible Implementation

Change to a more comfortable name

**Comment by ptrkdan** [comment]
As we discussed in our meeting, I think `code` (no `s`) sounds better. 👍
